### ISSUE TITLE
Feature request: OTA / Webinterface Update

### ISSUE THREAD

**Issue by Saharel001** [fredlcore/bsb_lan#132]
like https://github.com/jandrassy/ArduinoOTA

**Comment by fredlcore** [comment]
While this is theoretically possible (but quite difficult: https://forum.arduino.cc/index.php?topic=657425.0), it would require that the code uses less than 50% of the available flash so that the new firmware can be stored in the other half of the flash (this is the same on OTA functions on the ESP etc.). Since we are currently already consuming 54% of flash, this is no longer an option.

I don't know if it would be possible to do the upload in two stages (upload a small update program into flash, then switch to that program and then upload the new BSB-LAN code), but this would always be prone to errors and in the end could brick the Arduino. I don't think that this risk outweighs the benefit of an OTA function. 

Of course, if anyone has a different approach, I would be happy to have a look into it, but for the moment, I would be closing this issue.
