### ISSUE TITLE
unwanted 50Hz interaction on RX/TX

### ISSUE THREAD

**Issue by MariusOthermo** [fredlcore/bsb_lan#24]
Hello together,

I tried to simplify and build my own BSB/LPB board for the communication with an Elco boiler control. Because I wanted to use an Arduino I deleted the following parts from the original board: R11, R12, R13, Q11 and Q12. Attached you will find my new layout.

Now I connect DB/MB from the LBP and RX/TX to a logic analyser. If I connect 5V/GND over an TTL/USB adapter to a power bank or my laptop an expected signal will be transmitted. But if I connect 5V/GND to the Arduino (powered by cable) or if I connect my notebook/the power bank to the power outlet I get a wrong signal with some sort of 50Hz noise. Around every 20ms on channel 0 there is a signal but nothing happens on channel 1.

Is there a problem with the simplification of my board? I would be very happy, if somebody could help me with this problem. How can I get rid of this interaction between power adapter and signal? Thank you very much!

![Uploading signal analyzer ok and 50Hz noise.PNG…]()

**Comment by fredlcore** [comment]
Hi,
apart from the fact that the above attachment link returns to the issue itself, we already had a "simplified" board layout just for the Arduino at the beginning of this project (download one of the releases after 0.15 and before 0.25 I think). You may want to compare your layout to the one in the older releases and see if you notice any difference when using the board layout provided there.

Other than that, I'm sorry that I won't be able to assist you in this matter any further, a) because I'm not well versed in such details of electrical enginieering, and b) because this problem hasn't occurred in other people's setup who use the stock board layout provided here. That's why I have to focus the limited time that I can spend on this project to matters that affect a larger user base. Should your problem however also be reported by other users who use the stock board layout, I might reconsider. 

You may of course post your problem in the mentioned FHEM forum as there might be other users with more knowledge/time who might be able to help you.
