### ISSUE TITLE
BSB-LAN adapter connect RVS21.827/127

### ISSUE THREAD

**Issue by erelis77** [fredlcore/bsb_lan#42]
Hello,

I have a Siemens RVS21.827/127 heat pump controller Atlantic Alfea Excellia Duo. I made a BSB-LPB-LAN adapter. Please advise how to physically connect the BSB-LPB adapter to it.
![IMG_20191116_134955](https://user-images.githubusercontent.com/41342971/69057811-1cb15580-0a1b-11ea-8768-ef2caade7664.jpg)
![IMG_20191116_135008](https://user-images.githubusercontent.com/41342971/69057819-1fac4600-0a1b-11ea-9de7-514c2453b896.jpg)
![IMG_20191117_130149](https://user-images.githubusercontent.com/41342971/69057824-21760980-0a1b-11ea-935c-dd54c1c362b6.jpg)

**Comment by fredlcore** [comment]
This is not a support forum. If this board is the final result of your do-it-yourself work, then it seems that you didn't even read the schematics because several pins that need to be connected are not (such as 5V and GND). Other parts look rather "burnt", so I wouldn't vouch for this adapter to work. If you've tried everything and it doesn't work, there are still leftover boards from one of the last collective orders available. Send me an e-mail to bsb (ät) code-it.de for more info.
